INSERT INTO questions VALUES
(1, 1, 'What is a Python list and how is it different from a tuple?', 'Beginner', 'Python', 'spoken', '/audio/pytbeg001.wav'),
(2, 2, 'Explain the concept of Python decorators.', 'Beginner', 'Python', 'spoken', '/audio/pytbeg002.wav'),
(3, 3, 'How does Python handle memory management?', 'Beginner', 'Python', 'spoken', '/audio/pytbeg003.wav'),
(4, 4, 'What are Python''s data types?', 'Beginner', 'Python', 'spoken', '/audio/pytbeg004.wav'),
(5, 5, 'Explain the use of lambda functions in Python.', 'Beginner', 'Python', 'spoken', '/audio/pytbeg005.wav'),
(6, 6, 'Write a Python function to check if a string is a palindrome.', 'Beginner', 'Python', 'coding', NULL),
(7, 7, 'Write a Python program to generate Fibonacci series.', 'Beginner', 'Python', 'coding', NULL),
(8, 8, 'Implement a function to sort a list using bubble sort.', 'Beginner', 'Python', 'coding', NULL),
(9, 9, 'Write code to reverse a linked list in Python.', 'Beginner', 'Python', 'coding', NULL),
(10, 10, 'Implement binary search algorithm in Python.', 'Beginner', 'Python', 'coding', NULL),
(11, 11, 'What are Python''s generators and how do they work?', 'Intermediate', 'Python', 'spoken', '/audio/pytint011.wav'),
(12, 12, 'Can you explain Python''s GIL and its impact on threading?', 'Intermediate', 'Python', 'spoken', '/audio/pytint012.wav'),
(13, 13, 'What is the difference between deep copy and shallow copy in Python?', 'Intermediate', 'Python', 'spoken', '/audio/pytint013.wav'),
(14, 14, 'How does exception handling work in Python?', 'Intermediate', 'Python', 'spoken', '/audio/pytint014.wav'),
(15, 15, 'What are comprehensions in Python?', 'Intermediate', 'Python', 'spoken', '/audio/pytint015.wav'),
(16, 16, 'Write a function to count the frequency of elements in a list.', 'Intermediate', 'Python', 'coding', NULL),
(17, 17, 'Write a function to find the factorial of a number using recursion.', 'Intermediate', 'Python', 'coding', NULL),
(18, 18, 'Create a class in Python to represent a Bank Account.', 'Intermediate', 'Python', 'coding', NULL),
(19, 19, 'Write a script to read a file and count word frequency.', 'Intermediate', 'Python', 'coding', NULL),
(20, 20, 'Write a program to check for anagrams in Python.', 'Intermediate', 'Python', 'coding', NULL),
(21, 21, 'What are metaclasses in Python?', 'Advanced', 'Python', 'spoken', '/audio/pytadv021.wav'),
(22, 22, 'How does Python manage memory with reference cycles?', 'Advanced', 'Python', 'spoken', '/audio/pytadv022.wav'),
(23, 23, 'Explain the concept of coroutines and async in Python.', 'Advanced', 'Python', 'spoken', '/audio/pytadv023.wav'),
(24, 24, 'How can you optimize performance in Python scripts?', 'Advanced', 'Python', 'spoken', '/audio/pytadv024.wav'),
(25, 25, 'What are context managers and how do you create one?', 'Advanced', 'Python', 'spoken', '/audio/pytadv025.wav'),
(26, 26, 'Write a Python context manager using the with statement.', 'Advanced', 'Python', 'coding', NULL),
(27, 27, 'Build a custom iterator class in Python.', 'Advanced', 'Python', 'coding', NULL),
(28, 28, 'Create a multithreaded Python program to fetch data from APIs.', 'Advanced', 'Python', 'coding', NULL),
(29, 29, 'Use functools.lru_cache to memoize an expensive function.', 'Advanced', 'Python', 'coding', NULL),
(30, 30, 'Write a Python script to implement a producer-consumer pattern.', 'Advanced', 'Python', 'coding', NULL),
(31, 31, 'What is the difference between HTML and HTML5?', 'Beginner', 'Web Development', 'spoken', '/audio/webbeg031.wav'),
(32, 32, 'Explain how CSS specificity works.', 'Beginner', 'Web Development', 'spoken', '/audio/webbeg032.wav'),
(33, 33, 'What is the DOM and how does JavaScript interact with it?', 'Beginner', 'Web Development', 'spoken', '/audio/webbeg033.wav'),
(34, 34, 'What is the role of HTTP methods GET and POST?', 'Beginner', 'Web Development', 'spoken', '/audio/webbeg034.wav'),
(35, 35, 'What is the difference between localStorage and sessionStorage?', 'Beginner', 'Web Development', 'spoken', '/audio/webbeg035.wav'),
(36, 36, 'Create a basic HTML form with input validation using JavaScript.', 'Beginner', 'Web Development', 'coding', NULL),
(37, 37, 'Write JavaScript to fetch data from an API and display it.', 'Beginner', 'Web Development', 'coding', NULL),
(38, 38, 'Write a CSS snippet to create a responsive navigation bar.', 'Beginner', 'Web Development', 'coding', NULL),
(39, 39, 'Create a simple to-do list app using HTML, CSS, and JavaScript.', 'Beginner', 'Web Development', 'coding', NULL),
(40, 40, 'Write a JavaScript function to debounce an event handler.', 'Beginner', 'Web Development', 'coding', NULL),
(41, 41, 'How do you optimize a website''s performance?', 'Intermediate', 'Web Development', 'spoken', '/audio/webint041.wav'),
(42, 42, 'Explain responsive design and how to implement it.', 'Intermediate', 'Web Development', 'spoken', '/audio/webint042.wav'),
(43, 43, 'What are cookies and how are they used in web development?', 'Intermediate', 'Web Development', 'spoken', '/audio/webint043.wav'),
(44, 44, 'Explain RESTful APIs.', 'Intermediate', 'Web Development', 'spoken', '/audio/webint044.wav'),
(45, 45, 'What are some common security concerns in web development?', 'Intermediate', 'Web Development', 'spoken', '/audio/webint045.wav'),
(46, 46, 'Build a layout using CSS Grid or Flexbox.', 'Intermediate', 'Web Development', 'coding', NULL),
(47, 47, 'Create a JavaScript function to validate an email address.', 'Intermediate', 'Web Development', 'coding', NULL),
(48, 48, 'Build a simple static blog layout using HTML and CSS.', 'Intermediate', 'Web Development', 'coding', NULL),
(49, 49, 'Write a script to toggle a modal popup in JavaScript.', 'Intermediate', 'Web Development', 'coding', NULL),
(50, 50, 'Implement dark mode toggle in a webpage using JavaScript.', 'Intermediate', 'Web Development', 'coding', NULL),
(51, 51, 'What are service workers and how do they improve performance?', 'Advanced', 'Web Development', 'spoken', '/audio/webadv051.wav'),
(52, 52, 'Explain the critical rendering path in browsers.', 'Advanced', 'Web Development', 'spoken', '/audio/webadv052.wav'),
(53, 53, 'How does a virtual DOM differ from a real DOM?', 'Advanced', 'Web Development', 'spoken', '/audio/webadv053.wav'),
(54, 54, 'What is CORS and how do you handle it?', 'Advanced', 'Web Development', 'spoken', '/audio/webadv054.wav'),
(55, 55, 'What is SSR (Server Side Rendering) and its benefits?', 'Advanced', 'Web Development', 'spoken', '/audio/webadv055.wav'),
(56, 56, 'Write a custom JavaScript router for a single-page application.', 'Advanced', 'Web Development', 'coding', NULL),
(57, 57, 'Build a lazy-loaded image gallery using JavaScript.', 'Advanced', 'Web Development', 'coding', NULL),
(58, 58, 'Create a secure login form with client-side validation.', 'Advanced', 'Web Development', 'coding', NULL),
(59, 59, 'Build a responsive dashboard layout with charts using HTML/CSS/JS.', 'Advanced', 'Web Development', 'coding', NULL),
(60, 60, 'Write a fetch wrapper in JavaScript with timeout and retries.', 'Advanced', 'Web Development', 'coding', NULL),
(61, 61, 'Tell me about a time you handled a difficult conversation.', 'Beginner', 'Communication', 'spoken', '/audio/commbeg061.wav'),
(62, 62, 'How do you ensure clarity when communicating technical topics?', 'Beginner', 'Communication', 'spoken', '/audio/commbeg062.wav'),
(63, 63, 'Describe a situation where you had to give constructive feedback.', 'Beginner', 'Communication', 'spoken', '/audio/commbeg063.wav'),
(64, 64, 'How do you handle misunderstandings in a team setting?', 'Beginner', 'Communication', 'spoken', '/audio/commbeg064.wav'),
(65, 65, 'Explain how you prepare for a presentation.', 'Beginner', 'Communication', 'spoken', '/audio/commbeg065.wav'),
(66, 66, 'What is your approach to active listening?', 'Beginner', 'Communication', 'spoken', '/audio/commbeg066.wav'),
(67, 67, 'How do you respond when someone disagrees with you?', 'Beginner', 'Communication', 'spoken', '/audio/commbeg067.wav'),
(68, 68, 'What do you do to stay calm under pressure?', 'Beginner', 'Communication', 'spoken', '/audio/commbeg068.wav'),
(69, 69, 'Describe a time you successfully resolved a team conflict.', 'Beginner', 'Communication', 'spoken', '/audio/commbeg069.wav'),
(70, 70, 'How do you handle being misunderstood by a coworker?', 'Beginner', 'Communication', 'spoken', '/audio/commbeg070.wav'),
(71, 71, 'Describe a time when you had to persuade someone.', 'Intermediate', 'Communication', 'spoken', '/audio/commint071.wav'),
(72, 72, 'How do you adapt your communication style for different audiences?', 'Intermediate', 'Communication', 'spoken', '/audio/commint072.wav'),
(73, 73, 'Tell me about a time you resolved a conflict.', 'Intermediate', 'Communication', 'spoken', '/audio/commint073.wav'),
(74, 74, 'How do you manage communication in remote teams?', 'Intermediate', 'Communication', 'spoken', '/audio/commint074.wav'),
(75, 75, 'How do you handle giving negative feedback?', 'Intermediate', 'Communication', 'spoken', '/audio/commint075.wav'),
(76, 76, 'What communication channels do you prefer and why?', 'Intermediate', 'Communication', 'spoken', '/audio/commint076.wav'),
(77, 77, 'How do you deal with a non-responsive team member?', 'Intermediate', 'Communication', 'spoken', '/audio/commint077.wav'),
(78, 78, 'How do you keep your team informed without micromanaging?', 'Intermediate', 'Communication', 'spoken', '/audio/commint078.wav'),
(79, 79, 'Describe a presentation you gave and how it was received.', 'Intermediate', 'Communication', 'spoken', '/audio/commint079.wav'),
(80, 80, 'What do you do when you''re not sure how to respond to a question?', 'Intermediate', 'Communication', 'spoken', '/audio/commint080.wav'),
(81, 81, 'What motivates you to do your best work?', 'Advanced', 'Communication', 'spoken', '/audio/commadv081.wav'),
(82, 82, 'How do you define success?', 'Advanced', 'Communication', 'spoken', '/audio/commadv082.wav'),
(83, 83, 'Describe your ideal work environment.', 'Advanced', 'Communication', 'spoken', '/audio/commadv083.wav'),
(84, 84, 'How do you stay focused and productive throughout the day?', 'Advanced', 'Communication', 'spoken', '/audio/commadv084.wav'),
(85, 85, 'What do you consider your biggest professional achievement?', 'Advanced', 'Communication', 'spoken', '/audio/commadv085.wav'),
(86, 86, 'Tell me about a time you failed. How did you handle it?', 'Advanced', 'Communication', 'spoken', '/audio/commadv086.wav'),
(87, 87, 'What does leadership mean to you?', 'Advanced', 'Communication', 'spoken', '/audio/commadv087.wav'),
(88, 88, 'How do you balance work and personal life?', 'Advanced', 'Communication', 'spoken', '/audio/commadv088.wav'),
(89, 89, 'What do you do when you feel overwhelmed at work?', 'Advanced', 'Communication', 'spoken', '/audio/commadv089.wav'),
(90, 90, 'If you could change one thing about the way you work, what would it be?', 'Advanced', 'Communication', 'spoken', '/audio/commadv090.wav'),
(91, 91, 'What is object‑oriented programming (OOP) and why is it useful?', 'Beginner', 'OOP', 'spoken', '/audio/oopbeg001.wav'),
(92, 92, 'Explain the concept of classes and objects in OOP.', 'Beginner', 'OOP', 'spoken', '/audio/oopbeg002.wav'),
(93, 93, 'What is the difference between a class and an instance?', 'Beginner', 'OOP', 'spoken', '/audio/oopbeg003.wav'),
(94, 94, 'What are the four main principles of OOP?', 'Beginner', 'OOP', 'spoken', '/audio/oopbeg004.wav'),
(95, 95, 'Define encapsulation with an example.', 'Beginner', 'OOP', 'spoken', '/audio/oopbeg005.wav'),
(96, 96, 'Write a class in Python to represent a simple Rectangle.', 'Beginner', 'OOP', 'coding', NULL),
(97, 97, 'Create a class "Car" with attributes and a method to display car details.', 'Beginner', 'OOP', 'coding', NULL),
(98, 98, 'Write Python code to demonstrate constructor usage in a class.', 'Beginner', 'OOP', 'coding', NULL),
(99, 99, 'Implement a class that counts the number of its instances.', 'Beginner', 'OOP', 'coding', NULL),
(100, 100, 'Demonstrate how to use instance variables and methods in Python.', 'Beginner', 'OOP', 'coding', NULL),
(101, 101, 'What is inheritance and how is it implemented in Python?', 'Intermediate', 'OOP', 'spoken', '/audio/oopint011.wav'),
(102, 102, 'Explain the difference between single and multiple inheritance.', 'Intermediate', 'OOP', 'spoken', '/audio/oopint012.wav'),
(103, 103, 'What are class variables vs. instance variables?', 'Intermediate', 'OOP', 'spoken', '/audio/oopint013.wav'),
(104, 104, 'How does method overriding work in OOP?', 'Intermediate', 'OOP', 'spoken', '/audio/oopint014.wav'),
(105, 105, 'Explain the use of the super() function in inheritance.', 'Intermediate', 'OOP', 'spoken', '/audio/oopint015.wav'),
(106, 106, 'Write a base class "Animal" and a derived class "Dog" in Python.', 'Intermediate', 'OOP', 'coding', NULL),
(107, 107, 'Implement method overriding in Python using a parent and child class.', 'Intermediate', 'OOP', 'coding', NULL),
(108, 108, 'Create a class hierarchy to represent employees and managers.', 'Intermediate', 'OOP', 'coding', NULL),
(109, 109, 'Build a Python class with both class and instance methods.', 'Intermediate', 'OOP', 'coding', NULL),
(110, 110, 'Demonstrate multiple inheritance with a real-world example in Python.', 'Intermediate', 'OOP', 'coding', NULL),
(111, 111, 'What is polymorphism and how is it achieved in Python?', 'Advanced', 'OOP', 'spoken', '/audio/oopadv021.wav'),
(112, 112, 'Explain abstraction and how abstract base classes work in Python.', 'Advanced', 'OOP', 'spoken', '/audio/oopadv022.wav'),
(113, 113, 'What are magic methods in Python and how are they used?', 'Advanced', 'OOP', 'spoken', '/audio/oopadv023.wav'),
(114, 114, 'Describe the SOLID principles in OOP.', 'Advanced', 'OOP', 'spoken', '/audio/oopadv024.wav'),
(115, 115, 'What is the difference between composition and inheritance?', 'Advanced', 'OOP', 'spoken', '/audio/oopadv025.wav'),
(116, 116, 'Write a Python class using @abstractmethod from the abc module.', 'Advanced', 'OOP', 'coding', NULL),
(117, 117, 'Create a Python class that implements operator overloading for +.', 'Advanced', 'OOP', 'coding', NULL),
(118, 118, 'Build a composite class that uses composition to include other classes.', 'Advanced', 'OOP', 'coding', NULL),
(119, 119, 'Use magic methods to make a custom class iterable.', 'Advanced', 'OOP', 'coding', NULL),
(120, 120, 'Implement a plugin system using interfaces in Python.', 'Advanced', 'OOP', 'coding', NULL);